### ISSUE TITLE
"yo generator-gulp-angular-subtask" wrong command

### ISSUE THREAD

**Issue by poliveira89** [doronsever/generator-gulp-angular-subtask#3]
On the README.md file at the "Getting Started" section you mention on the 3rd step:

```
 yo generator-gulp-angular-subtask
```

But, apparently this is the right command:

```
 yo gulp-angular-subtask
```

I assume that was some kind of typo?

**Comment by doronsever** [comment]
yap... its a typo.
I will fix it.
10x

**Comment by poliveira89** [comment]
Sorry to bother with just a minor typo. Just was trying to help :smile: 

PS: Thank you for this project. Surely helps a lot. :+1:
