### ISSUE TITLE
generator-gulp-angular (version: 0.11.0) having a new file structure.

### ISSUE THREAD

**Issue by asim-qb** [doronsever/generator-gulp-angular-subtask#8]
generator-gulp-angular (version: 0.11.0) scaffolding is different. 

├──  src/
│   ├──  app/
│   │   ├──  components/
│   │   │   └──  navbar/
│   │   │   │   ├──  navbar.controller.js
│   │   │   │   └──  navbar.html
│   │   ├──  main/

Command yo gulp-angular-subtask:controller off-canvas-menu (without options) produces the structure:

├──  src/
│   ├──  app/
│   │   ├──  components/
│   │   │   └──  navbar/
│   │   │   │   ├──  controllers
│   │   │   │   │   └──  navbar.controller.js
│   │   │   │   ├──  spec
│   │   │   │   │   └──  controllers
│   │   │   │   │   │   └──  navbar.controller.spec.js

With options I can get what I want. But it will be great if I could permanently change --dest and other options.(I don't know how can I do this).

Or are you working on changing the file structure?

**Comment by doronsever** [comment]
Sorry for the late response, i'm working to support the new file structure.
I will upload it very soon
10x

**Comment by asim-qb** [comment]
Great to know that. :)
